/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package unocardgamesound;


public class About extends javax.swing.JFrame {

    /**
     * Creates new form About
     */
    public About() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        playButton = new javax.swing.JButton();
        aboutDescription = new javax.swing.JLabel();
        aboutTitle = new javax.swing.JLabel();
        HomeButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        AboutBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ABOUT");
        setLocation(new java.awt.Point(250, 20));
        setMaximumSize(new java.awt.Dimension(840, 760));
        setMinimumSize(new java.awt.Dimension(840, 760));
        setName("About"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        playButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unocardgamesound/images/playButton.png"))); // NOI18N
        playButton.setBorderPainted(false);
        playButton.setContentAreaFilled(false);
        playButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playButtonActionPerformed(evt);
            }
        });
        getContentPane().add(playButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 430, -1, -1));

        aboutDescription.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        aboutDescription.setText("<html>\n<p style=\"text-align: center;\">UNO is one of the most iconic classic games which we all grew to know and love!</p>\n<p style=\"text-align: center;\">Match cards either by matching <strong>&quot;C</strong><strong>olor&quot;</strong> or <strong>&quot;V</strong><strong>alue&quot;&nbsp;</strong>and play action cards to change things up.</p>\n<p style=\"text-align: center;\">The goal is to get rid of your cards before your opponents do.</p>\n<p style=\"text-align: center;\">When you have only one card left, don&#39;t forget to hit the&nbsp;</p>\n<p style=\"text-align: center;\">UNO button!</p>\n<p style=\"text-align: center;\"><br></p>\n</html>"); // NOI18N
        getContentPane().add(aboutDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 720, 340));
        aboutDescription.getAccessibleContext().setAccessibleName("");

        aboutTitle.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        aboutTitle.setForeground(new java.awt.Color(51, 51, 51));
        aboutTitle.setText("ABOUT THE GAME");
        getContentPane().add(aboutTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 330, -1));

        HomeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unocardgamesound/images/home.png"))); // NOI18N
        HomeButton.setContentAreaFilled(false);
        HomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(HomeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 550, 100, 80));

        CancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unocardgamesound/images/cancel.png"))); // NOI18N
        CancelButton.setContentAreaFilled(false);
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });
        getContentPane().add(CancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 610, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unocardgamesound/images/about image.png"))); // NOI18N
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 430, 420));

        AboutBackground.setBackground(new java.awt.Color(239, 255, 255));
        AboutBackground.setMaximumSize(new java.awt.Dimension(1040, 760));
        AboutBackground.setMinimumSize(new java.awt.Dimension(1040, 760));
        AboutBackground.setOpaque(true);
        AboutBackground.setPreferredSize(new java.awt.Dimension(1040, 760));
        getContentPane().add(AboutBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 850, 760));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void playButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playButtonActionPerformed
         Music m = new Music();
        m.buttonClick();
        new PlayerMode().setVisible(true);//Display the PlayerMode frame
	dispose();//close the current frame
    }//GEN-LAST:event_playButtonActionPerformed

    private void HomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeButtonActionPerformed
         Music m = new Music();
        m.buttonClick();
        new Menu().setVisible(true); // Displays the Main menu again
        dispose(); //close the current frame
    }//GEN-LAST:event_HomeButtonActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        Music m = new Music();
        m.buttonClick();
        System.exit(0);
    }//GEN-LAST:event_CancelButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new About().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AboutBackground;
    private javax.swing.JButton CancelButton;
    private javax.swing.JButton HomeButton;
    private javax.swing.JLabel aboutDescription;
    private javax.swing.JLabel aboutTitle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton playButton;
    // End of variables declaration//GEN-END:variables
}
