/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package unocardgamesound;

import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JOptionPane;


public class AddPlayerNames extends javax.swing.JFrame {
     public ArrayList<String> playerIds;
    /**
     * Creates new form AddPlayerNames
     */
    public AddPlayerNames() {
        initComponents();
        playerIds =new ArrayList<>();
    }
    
    public String[] getPids() {
		String pids[]= playerIds.toArray(new String[playerIds.size()]);
		return pids;
	}

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        playerIdtextField = new javax.swing.JTextField();
        PlayerId1lbl = new javax.swing.JLabel();
        PlayerId3lbl = new javax.swing.JLabel();
        PlayerId4lbl = new javax.swing.JLabel();
        PlayerId2lbl = new javax.swing.JLabel();
        SaveButton = new javax.swing.JButton();
        DoneButton = new javax.swing.JButton();
        DeleteButton = new javax.swing.JButton();
        PlayerId5lbl = new javax.swing.JLabel();
        PlayerId6lbl = new javax.swing.JLabel();
        PlayerId7lbl = new javax.swing.JLabel();
        PlayerId8lbl = new javax.swing.JLabel();
        PlayerId9lbl = new javax.swing.JLabel();
        PlayerId10lbl = new javax.swing.JLabel();
        BackGroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("UNO");
        setLocation(new java.awt.Point(300, 200));
        setMaximumSize(new java.awt.Dimension(626, 438));
        setMinimumSize(new java.awt.Dimension(626, 438));
        setName("AddPlayerNames"); // NOI18N
        setPreferredSize(new java.awt.Dimension(626, 438));
        setResizable(false);
        setSize(new java.awt.Dimension(626, 438));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 2, 35)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 51));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unocardgamesound/images/userIcon.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 90, 100));

        playerIdtextField.setFont(new java.awt.Font("Algerian", 1, 20)); // NOI18N
        playerIdtextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playerIdtextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(playerIdtextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 370, -1));

        PlayerId1lbl.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        PlayerId1lbl.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(PlayerId1lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 170, 30));

        PlayerId3lbl.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        PlayerId3lbl.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(PlayerId3lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 160, 30));

        PlayerId4lbl.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        PlayerId4lbl.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(PlayerId4lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, 200, 40));

        PlayerId2lbl.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        PlayerId2lbl.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(PlayerId2lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, 220, 30));

        SaveButton.setBackground(new java.awt.Color(255, 255, 102));
        SaveButton.setFont(new java.awt.Font("Algerian", 1, 30)); // NOI18N
        SaveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unocardgamesound/images/save_1.png"))); // NOI18N
        SaveButton.setBorderPainted(false);
        SaveButton.setContentAreaFilled(false);
        SaveButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SaveButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SaveButtonMouseExited(evt);
            }
        });
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });
        getContentPane().add(SaveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, -1));

        DoneButton.setBackground(new java.awt.Color(255, 255, 102));
        DoneButton.setFont(new java.awt.Font("Algerian", 1, 30)); // NOI18N
        DoneButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unocardgamesound/images/done_1.png"))); // NOI18N
        DoneButton.setBorderPainted(false);
        DoneButton.setContentAreaFilled(false);
        DoneButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DoneButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DoneButtonMouseExited(evt);
            }
        });
        DoneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoneButtonActionPerformed(evt);
            }
        });
        getContentPane().add(DoneButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 340, -1, -1));

        DeleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unocardgamesound/images/delete_1.png"))); // NOI18N
        DeleteButton.setContentAreaFilled(false);
        DeleteButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DeleteButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DeleteButtonMouseExited(evt);
            }
        });
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });
        getContentPane().add(DeleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, -1, -1));

        PlayerId5lbl.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        PlayerId5lbl.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(PlayerId5lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 200, 30));

        PlayerId6lbl.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        PlayerId6lbl.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(PlayerId6lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 230, 220, -1));

        PlayerId7lbl.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        PlayerId7lbl.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(PlayerId7lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 190, 30));

        PlayerId8lbl.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        PlayerId8lbl.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(PlayerId8lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, 220, 30));

        PlayerId9lbl.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        PlayerId9lbl.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(PlayerId9lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 180, 30));

        PlayerId10lbl.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        PlayerId10lbl.setForeground(new java.awt.Color(255, 255, 255));
        PlayerId10lbl.setMaximumSize(new java.awt.Dimension(11, 24));
        PlayerId10lbl.setMinimumSize(new java.awt.Dimension(11, 24));
        PlayerId10lbl.setPreferredSize(new java.awt.Dimension(11, 24));
        getContentPane().add(PlayerId10lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, 180, 30));

        BackGroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unocardgamesound/images/AddPlayers.jpg"))); // NOI18N
        BackGroundLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BackGroundLabel.setOpaque(true);
        getContentPane().add(BackGroundLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -60, 620, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
        if(playerIdtextField.getText().isEmpty())
				{       Music m = new Music();
        m.buttonClick();
					JLabel message=new JLabel("Please enter in a name");
					JOptionPane.showMessageDialog(null, message);
				}
        else if (playerIdtextField.getText().isBlank())
                                {
                                        Music m = new Music();
        m.buttonClick();
					JLabel message=new JLabel("Name cannot be all spaces");
					JOptionPane.showMessageDialog(null, message);
                                }
				
        else                    {  
                                         Music m = new Music();
                                     m.buttonClick();
					String name=playerIdtextField.getText().trim();
					playerIds.add(name);
					
					if (playerIds.size()==1)
					{
						PlayerId1lbl.setText(playerIds.get(0));
					}
					
					else if (playerIds.size()==2)
					{
						PlayerId1lbl.setText(playerIds.get(0));
						PlayerId2lbl.setText(playerIds.get(1));
					}
					
					else if (playerIds.size()==3)
					{
						PlayerId1lbl.setText(playerIds.get(0));
						PlayerId2lbl.setText(playerIds.get(1));
						PlayerId3lbl.setText(playerIds.get(2));
					}
					
					else if (playerIds.size()==4)
					{
						PlayerId1lbl.setText(playerIds.get(0));
						PlayerId2lbl.setText(playerIds.get(1));
						PlayerId3lbl.setText(playerIds.get(2));
						PlayerId4lbl.setText(playerIds.get(3));
					}
                                        else if (playerIds.size()==5)
					{
						PlayerId1lbl.setText(playerIds.get(0));
						PlayerId2lbl.setText(playerIds.get(1));
						PlayerId3lbl.setText(playerIds.get(2));
						PlayerId4lbl.setText(playerIds.get(3));
                                                PlayerId5lbl.setText(playerIds.get(4));
					}
                                        else if (playerIds.size()==6)
					{
						PlayerId1lbl.setText(playerIds.get(0));
						PlayerId2lbl.setText(playerIds.get(1));
						PlayerId3lbl.setText(playerIds.get(2));
						PlayerId4lbl.setText(playerIds.get(3));
                                                PlayerId5lbl.setText(playerIds.get(4));
                                                PlayerId6lbl.setText(playerIds.get(5));
                                        }
                                        else if (playerIds.size()==7)
					{
						PlayerId1lbl.setText(playerIds.get(0));
						PlayerId2lbl.setText(playerIds.get(1));
						PlayerId3lbl.setText(playerIds.get(2));
						PlayerId4lbl.setText(playerIds.get(3));
                                                PlayerId5lbl.setText(playerIds.get(4));
                                                PlayerId6lbl.setText(playerIds.get(5));
                                                PlayerId7lbl.setText(playerIds.get(6));
                                        }
                                        else if (playerIds.size()==8)
					{
						PlayerId1lbl.setText(playerIds.get(0));
						PlayerId2lbl.setText(playerIds.get(1));
						PlayerId3lbl.setText(playerIds.get(2));
						PlayerId4lbl.setText(playerIds.get(3));
                                                PlayerId5lbl.setText(playerIds.get(4));
                                                PlayerId6lbl.setText(playerIds.get(5));
                                                PlayerId7lbl.setText(playerIds.get(6));
                                                PlayerId8lbl.setText(playerIds.get(7));
                                        }
                                        else if (playerIds.size()==9)
					{
						PlayerId1lbl.setText(playerIds.get(0));
						PlayerId2lbl.setText(playerIds.get(1));
						PlayerId3lbl.setText(playerIds.get(2));
						PlayerId4lbl.setText(playerIds.get(3));
                                                PlayerId5lbl.setText(playerIds.get(4));
                                                PlayerId6lbl.setText(playerIds.get(5));
                                                PlayerId7lbl.setText(playerIds.get(6));
                                                PlayerId8lbl.setText(playerIds.get(7));
                                                PlayerId9lbl.setText(playerIds.get(8));
                                        }
                                        
                                        else if (playerIds.size()==10)
					{
						PlayerId1lbl.setText(playerIds.get(0));
						PlayerId2lbl.setText(playerIds.get(1));
						PlayerId3lbl.setText(playerIds.get(2));
						PlayerId4lbl.setText(playerIds.get(3));
                                                PlayerId5lbl.setText(playerIds.get(4));
                                                PlayerId6lbl.setText(playerIds.get(5));
                                                PlayerId7lbl.setText(playerIds.get(6));
                                                PlayerId8lbl.setText(playerIds.get(7));
                                                PlayerId9lbl.setText(playerIds.get(8));
                                                PlayerId10lbl.setText(playerIds.get(9));
					}
					
					if(playerIds.size()>0 && playerIds.size()<11) {
					
						playerIdtextField.setText(" ");
						 
					}
					
					if (playerIds.size()==11) {
						playerIds.remove(name);
						JLabel message=new JLabel("There can be only 10 Players");
						JOptionPane.showMessageDialog(null, message);
						playerIdtextField.setText(" ");
						
					}
				}
    }//GEN-LAST:event_SaveButtonActionPerformed

    private void playerIdtextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playerIdtextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_playerIdtextFieldActionPerformed

    private void DoneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoneButtonActionPerformed
        Music m = new Music();
        m.buttonClick();
        if (playerIds.size()==1 || playerIds.size()==0 )
	{
            JLabel message=new JLabel("There must be at least two Players");
            JOptionPane.showMessageDialog(null, message);
            playerIdtextField.setText(" ");
	}
				
	else
	{
            int points[]={0,0,0,0,0,0,0,0,0,0};
            dispose();//close the current frame 
            new GameStage(playerIds,points).setVisible(true); //Display the new frame  //playerIds
					
	}
    }//GEN-LAST:event_DoneButtonActionPerformed

    private void SaveButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SaveButtonMouseExited
        SaveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unocardgamesound/images/save_1.png")));
    }//GEN-LAST:event_SaveButtonMouseExited

    private void SaveButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SaveButtonMouseEntered
        SaveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unocardgamesound/images/save_2.png")));
    }//GEN-LAST:event_SaveButtonMouseEntered

    private void DoneButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DoneButtonMouseExited
        DoneButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unocardgamesound/images/done_1.png")));
    }//GEN-LAST:event_DoneButtonMouseExited

    private void DoneButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DoneButtonMouseEntered
        DoneButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unocardgamesound/images/done_2.png")));
    }//GEN-LAST:event_DoneButtonMouseEntered

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        if(PlayerId1lbl.getText().isEmpty())
        {
             Music m = new Music();
             m.buttonClick();
            JLabel message=new JLabel("Please enter a name first");
            JOptionPane.showMessageDialog(null, message);
        }
        else
        {
             Music m = new Music();
        m.buttonClick();
            int index = playerIds.size()-1;
            switch(playerIds.size())
            {
                case 1: {PlayerId1lbl.setText(null);break;}
                case 2: {PlayerId2lbl.setText(null);break;}
                case 3: {PlayerId3lbl.setText(null);break;}
                case 4: {PlayerId4lbl.setText(null);break;}
                case 5: {PlayerId5lbl.setText(null);break;}
                case 6: {PlayerId6lbl.setText(null);break;}
                case 7: {PlayerId7lbl.setText(null);break;}
                case 8: {PlayerId8lbl.setText(null);break;}
                case 9: {PlayerId9lbl.setText(null);break;}
                case 10: {PlayerId10lbl.setText(null);break;}
                
            }
            playerIds.remove(index);
        }
    }//GEN-LAST:event_DeleteButtonActionPerformed

    private void DeleteButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteButtonMouseExited
        DeleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unocardgamesound/images/delete_1.png")));
    }//GEN-LAST:event_DeleteButtonMouseExited

    private void DeleteButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteButtonMouseEntered
        DeleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unocardgamesound/images/delete_2.png")));
    }//GEN-LAST:event_DeleteButtonMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddPlayerNames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddPlayerNames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddPlayerNames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddPlayerNames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddPlayerNames().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackGroundLabel;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JButton DoneButton;
    private javax.swing.JLabel PlayerId10lbl;
    private javax.swing.JLabel PlayerId1lbl;
    private javax.swing.JLabel PlayerId2lbl;
    private javax.swing.JLabel PlayerId3lbl;
    private javax.swing.JLabel PlayerId4lbl;
    private javax.swing.JLabel PlayerId5lbl;
    private javax.swing.JLabel PlayerId6lbl;
    private javax.swing.JLabel PlayerId7lbl;
    private javax.swing.JLabel PlayerId8lbl;
    private javax.swing.JLabel PlayerId9lbl;
    private javax.swing.JButton SaveButton;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField playerIdtextField;
    // End of variables declaration//GEN-END:variables
}
