/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package unocardgamesound;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.stream.Collectors;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;


public class GameStage extends javax.swing.JFrame {

    /**
     * Creates new form GameStage
     */
  
     public static Boolean uno=false;
   
    public ArrayList<String> temp = new ArrayList<>();
    String pids[];
    Game game;
    ArrayList<JButton> cardButtons =new ArrayList<JButton>();
    ArrayList<String> cardIds;
    int p[]={0,0,0,0,0,0,0,0,0,0}; //points
    
    public GameStage(){}
    
    public GameStage(ArrayList<String>playerIds,int points[]) {
        initComponents();
        temp =playerIds;
        p=points;
	pids=temp.toArray(new String[temp.size()]);
        
        //create a game
	game= new Game(pids,points,this);
	populateArrayList();
	game.start(game); //start the game
	setPidName(); 
        
        //set the top card button
	topCardButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unocardgamesound/cardSprites/"+game.getTopCardImage())));
       //assign icon to card buttons
        setButtonIcons();
       
        
      
    }
    //set the icons to the buttons
    public void setButtonIcons() {
	String listString =game.getPlayerhand(game.getCurrentPlayer()).stream().map(Object::toString).collect(Collectors.joining(","));
	String cardNames[]=listString.split(",");
	cardIds=new ArrayList<>(Arrays.asList(cardNames));
        
        //assign icons to buttons when they are in the players hand
	for(int i=0;i<cardIds.size();i++) {
	       cardButtons.get(i).setIcon(new javax.swing.ImageIcon(getClass().getResource("/unocardgamesound/cardSprites/"+cardIds.get(i)+".png")));
        }
        
        //set the buttons to NULL if they are not in the player's hand
	for(int j=cardIds.size();j<cardButtons.size();j++)
	{
            cardButtons.get(j).setIcon(null);
	}
		
		
	}
  
    
            
//fill the arraylist cardButtons
public void populateArrayList(){
        cardButtons.add(jButton1);
	cardButtons.add(jButton2);
	cardButtons.add(jButton3);
	cardButtons.add(jButton4);
	cardButtons.add(jButton5);
	cardButtons.add(jButton6);
	cardButtons.add(jButton7);
        cardButtons.add(jButton8);
        cardButtons.add(jButton9);
        cardButtons.add(jButton10);
        cardButtons.add(jButton11);
	cardButtons.add(jButton12);
	cardButtons.add(jButton13);
	cardButtons.add(jButton14);
	cardButtons.add(jButton15);
	cardButtons.add(jButton16);
	cardButtons.add(jButton17);
        cardButtons.add(jButton18);
        cardButtons.add(jButton19);
        cardButtons.add(jButton20);
        cardButtons.add(jButton21);
        cardButtons.add(jButton22);
        
        
    }
    
//set the name label to current player's name
    public  void setPidName() {
	String currentPlayer =game.getCurrentPlayer();
	pidnameLabel.setText(currentPlayer+" 's Cards");
	}
    //set the name label to current player's name
    public  void setPidName(String currentPlayer)
	{  
	    
            pidnameLabel.setText(currentPlayer+" 's Cards");
	}

    
   
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        topCardButton = new javax.swing.JButton();
        downCard = new javax.swing.JButton();
        pidnameLabel = new javax.swing.JLabel();
        callUNOButton = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        ScoreButton = new javax.swing.JButton();
        home = new javax.swing.JButton();
        backGroundLabell = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("UNO");
        setName("GameStage"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(1600, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 140, 190));

        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 560, 140, 190));

        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 560, 140, 190));

        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 560, 140, 190));

        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 560, 140, 190));

        jButton6.setBorderPainted(false);
        jButton6.setContentAreaFilled(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 560, 140, 190));

        jButton7.setBorderPainted(false);
        jButton7.setContentAreaFilled(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 560, 140, 190));

        jButton8.setBorderPainted(false);
        jButton8.setContentAreaFilled(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 560, 140, 190));

        jButton9.setBorderPainted(false);
        jButton9.setContentAreaFilled(false);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 560, 140, 190));

        jButton10.setBorderPainted(false);
        jButton10.setContentAreaFilled(false);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 560, 140, 190));

        jButton11.setBorderPainted(false);
        jButton11.setContentAreaFilled(false);
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 560, 140, 190));

        topCardButton.setBorderPainted(false);
        topCardButton.setContentAreaFilled(false);
        topCardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                topCardButtonActionPerformed(evt);
            }
        });
        getContentPane().add(topCardButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 140, 140, 190));

        downCard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unocardgamesound/images/card_back_alt.png"))); // NOI18N
        downCard.setBorderPainted(false);
        downCard.setContentAreaFilled(false);
        downCard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                downCardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                downCardMouseExited(evt);
            }
        });
        downCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downCardActionPerformed(evt);
            }
        });
        getContentPane().add(downCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 140, 140, 190));

        pidnameLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        pidnameLabel.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(pidnameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 300, 40));

        callUNOButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unocardgamesound/images/button_uno.png"))); // NOI18N
        callUNOButton.setBorderPainted(false);
        callUNOButton.setContentAreaFilled(false);
        callUNOButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                callUNOButtonActionPerformed(evt);
            }
        });
        getContentPane().add(callUNOButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 60, 130, 80));

        jButton12.setBorderPainted(false);
        jButton12.setContentAreaFilled(false);
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 360, 140, 190));

        jButton13.setBorderPainted(false);
        jButton13.setContentAreaFilled(false);
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 360, 140, 190));

        jButton14.setBorderPainted(false);
        jButton14.setContentAreaFilled(false);
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 360, 140, 190));

        jButton15.setBorderPainted(false);
        jButton15.setContentAreaFilled(false);
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 360, 140, 190));

        jButton16.setBorderPainted(false);
        jButton16.setContentAreaFilled(false);
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 360, 140, 190));

        jButton17.setBorderPainted(false);
        jButton17.setContentAreaFilled(false);
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 360, 140, 190));

        jButton18.setBorderPainted(false);
        jButton18.setContentAreaFilled(false);
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 360, 140, 190));

        jButton19.setBorderPainted(false);
        jButton19.setContentAreaFilled(false);
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 360, 140, 190));

        jButton20.setBorderPainted(false);
        jButton20.setContentAreaFilled(false);
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 140, 190));

        jButton21.setBorderPainted(false);
        jButton21.setContentAreaFilled(false);
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 360, 140, 190));

        jButton22.setBorderPainted(false);
        jButton22.setContentAreaFilled(false);
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 140, 190));

        ScoreButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unocardgamesound/images/score_1.png"))); // NOI18N
        ScoreButton.setContentAreaFilled(false);
        ScoreButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ScoreButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ScoreButtonMouseExited(evt);
            }
        });
        ScoreButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ScoreButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ScoreButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 60, -1, -1));

        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unocardgamesound/images/restart_1.png"))); // NOI18N
        home.setContentAreaFilled(false);
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeMouseExited(evt);
            }
        });
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        getContentPane().add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 150, -1, -1));

        backGroundLabell.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unocardgamesound/images/greenBackground.jpg"))); // NOI18N
        getContentPane().add(backGroundLabell, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -20, 1600, 800));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(cardIds.get(2)!=null) {
       Music m = new Music();
        m.buttonClick();
	int index=2;
	String cardId=cardIds.get(2);
	press(cardId,game,index,cardButtons,this,topCardButton);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void topCardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_topCardButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_topCardButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(cardIds.get(1)!=null) {
          Music m = new Music();
        m.buttonClick();
	int index=1;
	String cardId=cardIds.get(1);
	press(cardId,game,index,cardButtons,this,topCardButton);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       if(cardIds.get(3)!=null) {
         Music m = new Music();
        m.buttonClick();
	int index=3;
	String cardId=cardIds.get(3);
	press(cardId,game,index,cardButtons,this,topCardButton);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if(cardIds.get(4)!=null) {
          Music m = new Music();
        m.buttonClick();
	int index=4;
	String cardId=cardIds.get(4);
	press(cardId,game,index,cardButtons,this,topCardButton);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if(cardIds.get(5)!=null) {
        Music m = new Music();
        m.buttonClick();
	int index=5;
	String cardId=cardIds.get(5);
	press(cardId,game,index,cardButtons,this,topCardButton);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        if(cardIds.get(6)!=null) {
	  Music m = new Music();
        m.buttonClick();
        int index=6;
	String cardId=cardIds.get(6);
	press(cardId,game,index,cardButtons,this,topCardButton);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
       if(cardIds.get(7)!=null) {
         Music m = new Music();
        m.buttonClick(); 
	int index=7;
	String cardId=cardIds.get(7);
	press(cardId,game,index,cardButtons,this,topCardButton);
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        if(cardIds.get(8)!=null) {
          Music m = new Music();
        m.buttonClick();   
	int index=8;
	String cardId=cardIds.get(8);
	press(cardId,game,index,cardButtons,this,topCardButton);
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        if(cardIds.get(10)!=null) {
         Music m = new Music();
        m.buttonClick();  
	int index=10;
	String cardId=cardIds.get(10);
	press(cardId,game,index,cardButtons,this,topCardButton);
        }
    }//GEN-LAST:event_jButton11ActionPerformed
   
    //this method is called when a player selects a card button to submit a card
    public void press(String cardName,Game game,int index,ArrayList<JButton> cardButtons,GameStage gamestage,JButton topCardButton)
    {
      ArrayList<UnoCard>playerHand;
   
       UnoCard.Color declaredColor; 
       
	this.game=game;
	playerHand=game.getPlayerhand(game.getCurrentPlayer());
	
	this.topCardButton=topCardButton;
        
        //if the player has selected a wild card then the pick color frame will be viisible otherise this will return the color of the selected card
        PickColorFrame pickColor=new PickColorFrame(game,this,topCardButton,game.getCurrentPlayer());
        declaredColor =pickColor.choseColor(playerHand.get(index));
	//color of the selected card  or the chosen color will be assigned to the declaredColor
        
	if(declaredColor!=null)
	{
          try {
              //submit the selected card
              game.submitPlayerCard(game.getCurrentPlayer(), playerHand.get(index), declaredColor);
         
          } 
          catch ( InvalidColorSubmissionException | InvalidValueSubmissionException | InvalidPlayerTurnException ex) {
               Logger.getLogger(GameStage.class.getName()).log(Level.SEVERE, null, ex);
          }
					
            
            revalidate();
            if(declaredColor!=UnoCard.Color.WILD) {
                setPidName(game.getCurrentPlayer());
                setButtonIcons();
               
               topCardButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unocardgamesound/cardSprites/"+game.getTopCardImage())));
              
            }
	}
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(cardIds.get(0)!=null) {
         Music m = new Music();
        m.buttonClick();
	int index=0;
	String cardId=cardIds.get(0);
        press(cardId,game,index,cardButtons,this,topCardButton); //when the player select a  card to submit calls the press () function
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void downCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downCardActionPerformed
        //players can draw cards by clicking on this button
         Music m = new Music();
        m.buttonClick();
        JLabel  message =new JLabel(game.getCurrentPlayer()+" drew a card!");
	JOptionPane.showMessageDialog(null, message);
	
        //player draws a card
        try {
                game.submitDraw(game.getCurrentPlayer());
	    }
	catch(InvalidPlayerTurnException ex) {
		java.util.logging.Logger.getLogger(GameStage.class.getName()).log(java.util.logging.Level.SEVERE,null,ex);
	}
	//set pid names and buttons after drawing a card   		
	this.setPidName(game.getCurrentPlayer());
	this.setButtonIcons();
    }//GEN-LAST:event_downCardActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        if(cardIds.get(9)!=null) {
          Music m = new Music();
        m.buttonClick();
	int index=9;
	String cardId=cardIds.get(9);
        press(cardId,game,index,cardButtons,this,topCardButton);
	
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void callUNOButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_callUNOButtonActionPerformed
         uno=false;
        if (game.getPlayerHandSize(game.getCurrentPlayer())==2)
        {
              Music m = new Music();
        m.uno();
            uno=true;
        }
       
    }//GEN-LAST:event_callUNOButtonActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        if(cardIds.get(11)!=null) {
         Music m = new Music();
        m.buttonClick();   
	int index=11;
	String cardId=cardIds.get(11);
	press(cardId,game,index,cardButtons,this,topCardButton);
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        if(cardIds.get(12)!=null) {
          Music m = new Music();
        m.buttonClick(); 
	int index=12;
	String cardId=cardIds.get(12);
	press(cardId,game,index,cardButtons,this,topCardButton);
        }
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        if(cardIds.get(13)!=null) {
          Music m = new Music();
        m.buttonClick();   
	int index=13;
	String cardId=cardIds.get(13);
	press(cardId,game,index,cardButtons,this,topCardButton);
        }
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
                if(cardIds.get(14)!=null) {
          Music m = new Music();
        m.buttonClick();   
	int index=14;
	String cardId=cardIds.get(14);
	press(cardId,game,index,cardButtons,this,topCardButton);
        }
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
                if(cardIds.get(15)!=null) {
         Music m = new Music();
        m.buttonClick();   
	int index=15;
	String cardId=cardIds.get(15);
	press(cardId,game,index,cardButtons,this,topCardButton);
        }
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
                if(cardIds.get(16)!=null) {
          Music m = new Music();
        m.buttonClick(); 
	int index=16;
	String cardId=cardIds.get(16);
	press(cardId,game,index,cardButtons,this,topCardButton);
        }
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
                if(cardIds.get(17)!=null) {
         Music m = new Music();
        m.buttonClick();    
	int index=17;
	String cardId=cardIds.get(17);
	press(cardId,game,index,cardButtons,this,topCardButton);
        }
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
               if(cardIds.get(18)!=null) {
         Music m = new Music();
        m.buttonClick();   
	int index=18;
	String cardId=cardIds.get(18);
	press(cardId,game,index,cardButtons,this,topCardButton);
        }
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
               if(cardIds.get(19)!=null) {
         Music m = new Music();
        m.buttonClick();    
	int index=19;
	String cardId=cardIds.get(19);
	press(cardId,game,index,cardButtons,this,topCardButton);
        }
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        if(cardIds.get(20)!=null) {
         Music m = new Music();
        m.buttonClick();  
	int index=20;
	String cardId=cardIds.get(20);
	press(cardId,game,index,cardButtons,this,topCardButton);
        }
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        if(cardIds.get(21)!=null) {
             Music m = new Music();
        m.buttonClick();
            int index=21;
            String cardId=cardIds.get(21);
            press(cardId,game,index,cardButtons,this,topCardButton);
        }
    }//GEN-LAST:event_jButton22ActionPerformed

    private void ScoreButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ScoreButtonActionPerformed
         Music m = new Music();
        m.buttonClick();
      
        new Scores(temp,p).setVisible(true);
    }//GEN-LAST:event_ScoreButtonActionPerformed

    private void ScoreButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ScoreButtonMouseEntered
        ScoreButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unocardgamesound/images/score_2.png")));
    }//GEN-LAST:event_ScoreButtonMouseEntered

    private void ScoreButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ScoreButtonMouseExited
        ScoreButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unocardgamesound/images/score_1.png")));
    }//GEN-LAST:event_ScoreButtonMouseExited

    private void downCardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_downCardMouseEntered
       downCard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unocardgamesound/images/card_back_alt_hover.png")));
    }//GEN-LAST:event_downCardMouseEntered

    private void downCardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_downCardMouseExited
        downCard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unocardgamesound/images/card_back_alt.png")));
    }//GEN-LAST:event_downCardMouseExited

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        Music m = new Music();
       m.buttonClick();
       new Menu().setVisible(true);
       dispose();
    }//GEN-LAST:event_homeActionPerformed

    private void homeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseExited
       home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unocardgamesound/images/restart_1.png")));
    }//GEN-LAST:event_homeMouseExited

    private void homeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseEntered
        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unocardgamesound/images/restart_2.png")));
    }//GEN-LAST:event_homeMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameStage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameStage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameStage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameStage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameStage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ScoreButton;
    private javax.swing.JLabel backGroundLabell;
    private javax.swing.JButton callUNOButton;
    private javax.swing.JButton downCard;
    private javax.swing.JButton home;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel pidnameLabel;
    private javax.swing.JButton topCardButton;
    // End of variables declaration//GEN-END:variables
}
