/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package unocardgamesound;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;


public class PickColorFrame extends javax.swing.JFrame {

   Boolean allow=false;
   Game game;
   GameStage gameStage;
   
   JButton topCardButton;
   String currentPlayer;
    
    public PickColorFrame(Game game,GameStage gameStage, JButton topCardButton,String currentPlayer) {
        initComponents();
         this.game=game;
         this.gameStage=gameStage;
         this.topCardButton=topCardButton;
         this.currentPlayer=currentPlayer;
         
    }
    
  
    
    public PickColorFrame( ) {
        initComponents();
       
    }
    
    public UnoCard.Color choseColor(UnoCard card)
	{    
            //if the selected card is a wild card then the pickcolor frame will be visisble and the player will get the chance to select a color
            if (card.getColor()==UnoCard.Color.WILD)
            {
		setVisible(true);
		setResizable(false);
		
		 
            }
            return card.getColor();
	}

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        redButton = new javax.swing.JButton();
        blueButton = new javax.swing.JButton();
        greenButton = new javax.swing.JButton();
        yellowButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(100, 100, 0, 0));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        redButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unocardgamesound/images/redCard.png"))); // NOI18N
        redButton.setBorderPainted(false);
        redButton.setContentAreaFilled(false);
        redButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redButtonActionPerformed(evt);
            }
        });
        getContentPane().add(redButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 80, -1));

        blueButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unocardgamesound/images/blueCard.png"))); // NOI18N
        blueButton.setBorderPainted(false);
        blueButton.setContentAreaFilled(false);
        blueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blueButtonActionPerformed(evt);
            }
        });
        getContentPane().add(blueButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 80, -1));

        greenButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unocardgamesound/images/GreeenCard.png"))); // NOI18N
        greenButton.setBorderPainted(false);
        greenButton.setContentAreaFilled(false);
        greenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                greenButtonActionPerformed(evt);
            }
        });
        getContentPane().add(greenButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 70, -1));

        yellowButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unocardgamesound/images/yellowCard.png"))); // NOI18N
        yellowButton.setBorderPainted(false);
        yellowButton.setContentAreaFilled(false);
        yellowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yellowButtonActionPerformed(evt);
            }
        });
        getContentPane().add(yellowButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 120, 80, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Choose a Color!");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Hansi Karunarathna\\Desktop\\uno\\GameImages\\0011693_calendula-beige-modern-floral_600.jpeg")); // NOI18N
        jLabel1.setName(""); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void redButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redButtonActionPerformed
         Music m = new Music();
        m.buttonClick();
	JLabel message=new JLabel("The Wild Card Color is RED");
	JOptionPane.showMessageDialog(null, message);
	allow=true;
	dispose();
	gameStage.setPidName(game.getCurrentPlayer());
        gameStage.setButtonIcons();
	
	topCardButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unocardgamesound/cardSprites/"+game.getTopCardImage())));
        game.setCardColor(UnoCard.Color.RED);
	
    }//GEN-LAST:event_redButtonActionPerformed

    private void blueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blueButtonActionPerformed
           Music m = new Music();
        m.buttonClick();
	JLabel message=new JLabel("The Wild Card Color is BLUE");
	JOptionPane.showMessageDialog(null, message);
	allow=true;
	dispose();
	gameStage.setPidName(game.getCurrentPlayer());
        gameStage.setButtonIcons();
	
	topCardButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unocardgamesound/cardSprites/"+game.getTopCardImage())));
        game.setCardColor(UnoCard.Color.BLUE);
    }//GEN-LAST:event_blueButtonActionPerformed

    private void greenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_greenButtonActionPerformed
        Music m = new Music();
        m.buttonClick();
	JLabel message=new JLabel("The Wild Card Color is GREEN");
	JOptionPane.showMessageDialog(null, message);
	allow=true;
	dispose();
        
	gameStage.setPidName(game.getCurrentPlayer());
        gameStage.setButtonIcons();
	
        topCardButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unocardgamesound/cardSprites/"+game.getTopCardImage())));
	game.setCardColor(UnoCard.Color.GREEN);
        
    }//GEN-LAST:event_greenButtonActionPerformed

    private void yellowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yellowButtonActionPerformed
         Music m = new Music();
        m.buttonClick();
	JLabel message=new JLabel("The Wild Card Color is YELLOW");
	JOptionPane.showMessageDialog(null, message);
	allow=true;
	dispose();
	gameStage.setPidName(game.getCurrentPlayer());
        gameStage.setButtonIcons();
	
	topCardButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unocardgamesound/cardSprites/"+game.getTopCardImage())));
        game.setCardColor(UnoCard.Color.YELLOW);
    }//GEN-LAST:event_yellowButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PickColorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PickColorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PickColorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PickColorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PickColorFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton blueButton;
    private javax.swing.JButton greenButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton redButton;
    private javax.swing.JButton yellowButton;
    // End of variables declaration//GEN-END:variables
}
