/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package unocardgamesound;

import java.util.ArrayList;


public class Scores extends javax.swing.JFrame {

    /**
     * Creates new form Scores
     */
    public Scores() {
        initComponents();
    }
    
    public Scores( ArrayList<String> playerIds, int points[]) {
        
        initComponents();
        String pids[]= playerIds.toArray(new String[playerIds.size()]);
        int size=pids.length;  // 1 1 1 1 1
        
        if(1<=size){
             p1.setText(pids[0]);
             s1.setText(Integer.toString(points[0]));
        }
           
        if(2<=size){
            p2.setText(pids[1]);
            s2.setText(Integer.toString(points[1]));
        }
        if(3<=size){
            p3.setText(pids[2]);
            s3.setText(Integer.toString(points[2]));
        }
        if(4<=size){
            p4.setText(pids[3]);
            s4.setText(Integer.toString(points[3]));
        }
        if(5<=size){
            p5.setText(pids[4]);
            s5.setText(Integer.toString(points[4]));
        }
        if(6<=size){
            p6.setText(pids[5]);
            s6.setText(Integer.toString(points[5]));
        }
        if(7<=size){
            p7.setText(pids[6]);
            s7.setText(Integer.toString(points[6]));
        }
        if(8<=size){
            p8.setText(pids[7]);
            s8.setText(Integer.toString(points[7]));
        }
        if(9<=size){
            p9.setText(pids[8]);
            s9.setText(Integer.toString(points[8]));
        }
        if(10<=size){
            p10.setText(pids[9]);
            s10.setText(Integer.toString(points[9]));
        }
     

                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        p1 = new javax.swing.JLabel();
        p2 = new javax.swing.JLabel();
        p3 = new javax.swing.JLabel();
        p4 = new javax.swing.JLabel();
        p5 = new javax.swing.JLabel();
        p6 = new javax.swing.JLabel();
        p7 = new javax.swing.JLabel();
        p8 = new javax.swing.JLabel();
        p9 = new javax.swing.JLabel();
        p10 = new javax.swing.JLabel();
        s1 = new javax.swing.JLabel();
        s2 = new javax.swing.JLabel();
        s3 = new javax.swing.JLabel();
        s4 = new javax.swing.JLabel();
        s5 = new javax.swing.JLabel();
        s6 = new javax.swing.JLabel();
        s7 = new javax.swing.JLabel();
        s8 = new javax.swing.JLabel();
        s9 = new javax.swing.JLabel();
        s10 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        CloseButton = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SCORES");
        setLocation(new java.awt.Point(100, 100));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        p1.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        p1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        getContentPane().add(p1, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 49, 186, 26));

        p2.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        getContentPane().add(p2, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 86, 186, 26));

        p3.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        getContentPane().add(p3, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 123, 186, 26));

        p4.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        getContentPane().add(p4, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 160, 186, 26));

        p5.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        getContentPane().add(p5, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 197, 186, 26));

        p6.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        getContentPane().add(p6, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 229, 186, 26));

        p7.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        getContentPane().add(p7, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 269, 186, 26));

        p8.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        getContentPane().add(p8, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 306, 186, 26));

        p9.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        getContentPane().add(p9, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 343, 186, 26));

        p10.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        getContentPane().add(p10, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 380, 186, 26));

        s1.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        getContentPane().add(s1, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 56, 76, -1));

        s2.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        getContentPane().add(s2, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 93, 76, -1));

        s3.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        getContentPane().add(s3, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 130, 76, -1));

        s4.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        getContentPane().add(s4, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 167, 76, -1));

        s5.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        getContentPane().add(s5, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 204, 76, -1));

        s6.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        getContentPane().add(s6, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 229, 76, 29));

        s7.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        getContentPane().add(s7, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 276, 76, -1));

        s8.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        getContentPane().add(s8, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 313, 76, -1));

        s9.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        getContentPane().add(s9, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 350, 76, -1));

        s10.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        getContentPane().add(s10, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 387, 76, -1));

        jLabel22.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        jLabel22.setText("SCORE BOARD");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        CloseButton.setText("CLOSE");
        CloseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseButtonActionPerformed(evt);
            }
        });
        getContentPane().add(CloseButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, -1, -1));

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setOpaque(true);
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 490, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CloseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseButtonActionPerformed
       this.dispose();
    }//GEN-LAST:event_CloseButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Scores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Scores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Scores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Scores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Scores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CloseButton;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel p1;
    private javax.swing.JLabel p10;
    private javax.swing.JLabel p2;
    private javax.swing.JLabel p3;
    private javax.swing.JLabel p4;
    private javax.swing.JLabel p5;
    private javax.swing.JLabel p6;
    private javax.swing.JLabel p7;
    private javax.swing.JLabel p8;
    private javax.swing.JLabel p9;
    private javax.swing.JLabel s1;
    private javax.swing.JLabel s10;
    private javax.swing.JLabel s2;
    private javax.swing.JLabel s3;
    private javax.swing.JLabel s4;
    private javax.swing.JLabel s5;
    private javax.swing.JLabel s6;
    private javax.swing.JLabel s7;
    private javax.swing.JLabel s8;
    private javax.swing.JLabel s9;
    // End of variables declaration//GEN-END:variables
}
