/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package unocardgamesound;


public class ScoreDisplay extends javax.swing.JFrame {

    /**
     * Creates new form ScoreDisplay
     */
    
    public ScoreDisplay() {
        initComponents();     
    }
   public ScoreDisplay(int points[]) {
        initComponents();
        Score_1.setText(Integer.toString(points[1]));
        Score_2.setText(Integer.toString(points[0]));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        playerName_1 = new javax.swing.JLabel();
        playerName_2 = new javax.swing.JLabel();
        Score_1 = new javax.swing.JLabel();
        Score_2 = new javax.swing.JLabel();
        Closebutton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ScoreChart");
        setLocation(new java.awt.Point(100, 100));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        playerName_1.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        playerName_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        playerName_1.setText("Player");
        jPanel1.add(playerName_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 140, 42));

        playerName_2.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        playerName_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        playerName_2.setText("PC");
        jPanel1.add(playerName_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 130, 42));

        Score_1.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        Score_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(Score_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 97, 40));

        Score_2.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        Score_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(Score_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 97, -1));

        Closebutton.setText("CANCEL");
        Closebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClosebuttonActionPerformed(evt);
            }
        });
        jPanel1.add(Closebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unocardgamesound/images/Unoscore.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, -1, -1));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 290));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ClosebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClosebuttonActionPerformed
        this.dispose();
    }//GEN-LAST:event_ClosebuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScoreDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScoreDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScoreDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScoreDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScoreDisplay().setVisible(true);
            }
            
        });
    }
    
        
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Closebutton;
    private javax.swing.JLabel Score_1;
    private javax.swing.JLabel Score_2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel playerName_1;
    private javax.swing.JLabel playerName_2;
    // End of variables declaration//GEN-END:variables
}
