/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package unocardgamesound;


public class SpecialCards extends javax.swing.JFrame {

    /**
     * Creates new form SpecialCards
     */
    public SpecialCards() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        BackButton = new javax.swing.JButton();
        HomeButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        REVERSE = new javax.swing.JLabel();
        SKIP = new javax.swing.JLabel();
        DT = new javax.swing.JLabel();
        WILD = new javax.swing.JLabel();
        WDF = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ACTION CARDS");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unocardgamesound/images/about image.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 330, -1));

        BackButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unocardgamesound/images/BackButton.png"))); // NOI18N
        BackButton.setContentAreaFilled(false);
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        getContentPane().add(BackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 580, -1, -1));

        HomeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unocardgamesound/images/home.png"))); // NOI18N
        HomeButton.setContentAreaFilled(false);
        HomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(HomeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 570, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setText("ACTION CARDS");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 30, -1, -1));

        REVERSE.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        REVERSE.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        REVERSE.setText("<html>\n <p style=\"text-align: center;\"><strong>REVERSE</strong></p>\nWhen this card is played, the direction of the game changes. \n<br>This card can only be played on a card of the same colour or on another 'REVERSE' card</br>\n</html>");
        REVERSE.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(REVERSE, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 350, 320));

        SKIP.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        SKIP.setText("<html>\n <p style=\"text-align: center;\"><strong>SKIP</strong></p>\nWhen this card is played, the next player simply skips his/her turn.\n<br>This card can only be played on a card of the same color or on another 'SKIP' card.</br>\n<br>If turned up at the beginning of the play, the first player loses his/her turn.</br>\n<br>The next player starts the game instead.</br>\n</html>");
        getContentPane().add(SKIP, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, 280, -1));

        DT.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        DT.setText("<html>\n <p style=\"text-align: center;\"><strong>DRAW TWO</strong></p>\nWhen this card is played, the following player must draw 2 cards from the deck and skips his/her turn. \n<br>This card can only be played on a card of the same color or on another 'Draw Two'.</br>\n<br>If turned up at the beginning of the play, the first player draws two cards and gets skipped.</br>\n</html>\n");
        getContentPane().add(DT, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 130, 290, -1));

        WILD.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        WILD.setText("<html>\n<p style=\"text-align: center;\"><strong>WILD</strong></p>\nThe player who plays this card can choose to change the current color or to continue with the same color.\n<br>If it is the first card of the stock, then the first player must choose the starting color.</br>\n<br>This card can be played on any other card.</br>\n</html>");
        getContentPane().add(WILD, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 130, 330, -1));

        WDF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        WDF.setText("<html>\n<p style=\"text-align: center;\"><strong>WILD DRAW FOUR</strong></p>\nWhen this card is played, not only the following player must draw 4 cards of the deck, but he/she must also skip the turn.\n<br>Then, the current player can choose the color in which the game is going to continue.</br>\n<br>If turned up at the beginning of the play, return this card to the Draw pile, shuffle, and turn up a new one.</br>\n<br>This card can be played on any other card.</br>\n</html>");
        getContentPane().add(WDF, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 440, 630, -1));

        jLabel1.setBackground(new java.awt.Color(239, 255, 255));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, 0, 1540, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeButtonActionPerformed
         Music m = new Music();
        m.buttonClick();
        new Menu().setVisible(true); // Displays the Main menu again
        dispose(); //close the current frame
    }//GEN-LAST:event_HomeButtonActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
         Music m = new Music();
        m.buttonClick();
        new Instructions().setVisible(true); // Displays the Instructions menu again
        dispose(); //close the current frame
    }//GEN-LAST:event_BackButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SpecialCards.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SpecialCards.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SpecialCards.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SpecialCards.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SpecialCards().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JLabel DT;
    private javax.swing.JButton HomeButton;
    private javax.swing.JLabel REVERSE;
    private javax.swing.JLabel SKIP;
    private javax.swing.JLabel WDF;
    private javax.swing.JLabel WILD;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
